server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: buyer-service
          uri: lb://buyer-service
          predicates:
            Path=/buyer/**
          filters:
            - AuthFilter

        - id: admin-service
          uri: lb://admin-service
          predicates:
            Path=/admin/**
          filters:
            - AuthFilter

        - id: auth-service
          uri: lb://auth-service
          predicates:
            Path=/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
