server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            Path=/users/**

        - id: admin-service
          uri: lb://admin-service
          predicates:
            Path=/admin/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            Path=/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    prefer-ip-address: true
