server:
  port: 0

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/product_shop
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        show_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    prefer-ip-address: true